# version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web

  nuclei:
    image: projectdiscovery/nuclei:latest
    command: ["-u", "http://web:8000", "-silent", "-o", "/nuclei-logs/output.json"]
    volumes:
      - ./nuclei-logs:/nuclei-logs
    networks:
      - webnet
    depends_on:
      - web

networks:
  webnet:
