# version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - webnet

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - webnet

  nuclei:
    image: projectdiscovery/nuclei:latest
    command: ["-u", "http://web:5000", "-silent", "-o", "/nuclei-logs/output.json"]
    volumes:
      - ./nuclei-logs:/nuclei-logs
    networks:
      - webnet
    depends_on:
      - web

networks:
  webnet:
